export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"

export const RECOVERY_START = "RECOVERY_START"
export const RECOVERY_SUCCESS = "RECOVERY_SUCCESS"
export const RECOVERY_FAIL = "RECOVERY_FAIL"

export const CLEAN_UP = "CLEAN_UP"

export const VERIFY_START = "VERIFY_START"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_FAIL = "VERIFY_FAIL"

export const PROFILE_EDIT_START = "PROFILE_EDIT_START"
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS"
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL"

export const DELETE_PROFILE_START = "DELETE_PROFILE_START"
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS"
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL"

export const PFP_EDIT_START = "PFP_EDIT_START"
export const PFP_EDIT_SUCCESS = "PFP_EDIT_SUCCESS"
export const PFP_EDIT_FAIL = "PFP_EDIT_FAIL"

export const ACCEPT_INVITE_START = "ACCEPT_INVITE_START"
export const ACCEPT_INVITE_SUCCESS = "ACCEPT_INVITE_SUCCESS"
export const ACCEPT_INVITE_FAIL = "ACCEPT_INVITE_FAIL"

export const SEND_INVITE_START = "SEND_INVITE_START"
export const SEND_INVITE_SUCCESS = "SEND_INVITE_SUCCESS"
export const SEND_INVITE_FAIL = "SEND_INVITE_FAIL"

export const DELETE_INVITE_START = "DELETE_INVITE_START"
export const DELETE_INVITE_SUCCESS = "DELETE_INVITE_SUCCESS"
export const DELETE_INVITE_FAIL = "DELETE_INVITE_FAIL"

export const DELETE_FRIEND_START = "DELETE_FRIEND_START"
export const DELETE_FRIEND_SUCCESS = "DELETEFRIEND_SUCCESS"
export const DELETE_FRIEND_FAIL = "DELETE_FRIEND_FAIL"