export const LANDING = '/'
export const SIGN_UP = '/signup'
export const LOG_OUT = '/logout'
export const HOME = '/home'
export const SIDEDRAWER = '/sidedrawer'
export const PASSWORD_RESET = '/password_reset'
export const PROFILE = '/profile'
export const PROFILE_EDIT = '/profile_edit'
export const ABOUT = '/about'
export const EMAIL_VERIFICATION = '/email_verification'
export const ADD_FRIENDS = '/add_friends'
export const DISPLAY_FRIENDS = '/display_friends'
export const PICK_FOOD = '/pick_food'
export const MENU = '/menu'

export const MAP = '/map'
export const TWILIO = '/twilio'