export const AUTH_START = "AUTH_START"
export const AUTH_END = "AUTH_END"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"

export const RECOVERY_START = "RECOVERY_START"
export const RECOVERY_SUCCESS = "RECOVERY_SUCCESS"
export const RECOVERY_FAIL = "RECOVERY_FAIL"

export const CLEAN_UP = "CLEAN_UP"
export const CLOSE_SIDE_DRAWER = "CLOSE_SIDE_DRAWER"
export const OPEN_SIDE_DRAWER = "OPEN_SIDE_DRAWER"
