export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"

export const RECOVERY_START = "RECOVERY_START"
export const RECOVERY_SUCCESS = "RECOVERY_SUCCESS"
export const RECOVERY_FAIL = "RECOVERY_FAIL"

export const CLEAN_UP = "CLEAN_UP"

export const CLOSE_SIDE_DRAWER = "CLOSE_SIDE_DRAWER"
export const OPEN_SIDE_DRAWER = "OPEN_SIDE_DRAWER"
export const CHANGE_SIDE_DRAWER = "CHANGE_SIDE_DRAWER"

export const VERIFY_START = "VERIFY_START"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_FAIL = "VERIFY_FAIL"

export const PROFILE_EDIT_START = "PROFILE_EDIT_START"
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS"
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL"

export const ACCEPT_INVITE_START = "ACCEPT_INVITE_START"
export const ACCEPT_INVITE_SUCCESS = "ACCEPT_INVITE_SUCCESS"
export const ACCEPT_INVITE_FAIL = "ACCEPT_INVITE_FAIL"

export const SEND_INVITE_START = "SEND_INVITE_START"
export const SEND_INVITE_SUCCESS = "SEND_INVITE_SUCCESS"
export const SEND_INVITE_FAIL = "SEND_INVITE_FAIL"

export const DELETE_INVITE_START = "SEND_INVITE_START"
export const DELETE_INVITE_SUCCESS = "SEND_INVITE_SUCCESS"
export const DELETE_INVITE_FAIL = "SEND_INVITE_FAIL"